### ISSUE TITLE
Show network name next to the logo

### ISSUE THREAD

**Issue by kimwz** [planetarium/9cscan.com#10]
We currently run several networks and 9cscan such as odin, heimdall and thor. 

It would be good to show the network name next to the top logo to distinguish which 9cscan corresponds to each network.

**Comment by 12hyo12** [comment]
핵토버페스트2024 참가자 안효원입니다.

**Comment by kimwz** [comment]
solved https://github.com/planetarium/9cscan.com/pull/11
